global:
  scrape_interval:     30s
  evaluation_interval: 1m

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: [
          '192.168.1.198:9090'
      ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [
          '192.168.1.198:9100'          
      ]
          
  - job_name: 'rpi_exporter'
    static_configs:
      - targets: [
          '192.168.1.198:9243'
      ]
  - job_name: 'vedirect'
    static_configs:
      - targets: [
          '192.168.1.198:7090'
      ]
